#!/bin/sh

# Simple wrapper script for when you used CPAN with local::lib to
# install Parser::MGC, and don't want to pollute your environment
# with the stuff for local::lib.

perl5="$HOME/perl5"
PATH="$perl5/bin${PATH:+:${PATH}}"; export PATH;
PERL5LIB="$perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
PERL_LOCAL_LIB_ROOT="$perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
PERL_MB_OPT="--install_base \"$perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=$perl5"; export PERL_MM_OPT;
# Call twixt.pl with the same path
$0.pl "$@"
